# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#
# # list of Resource Config to be Applied
resources:
- ../../base

#
# # namespace to deploy all Resources to
namespace: flask
#
# # labels added to all Resources
commonLabels:
   app: flask
   env: development
#     
