apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: flask
    env: staging
    monitor: prometheus
    release: monitoring
  name: monitoring-staging
  namespace: monitoring
spec:
  endpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      app: flask
      env: staging
