apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: flask
    app.kubernetes.io/instance: staging-flask
    env: staging
  name: monitoring-staging
  namespace: monitoring
spec:
  endpoints:
    - path: /metrics
      port: service
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      app: flask
      env: staging
