apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-blog
  name: flask-blog
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-blog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-blog
    spec:
      containers:
      - image: 207080326074.dkr.ecr.ap-southeast-1.amazonaws.com/flask_blog
        imagePullPolicy: Always
        name: flask-blog-7d7s2
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
