apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-blog
  name: flask-blog
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    name: http
  selector:
    app: flask-blog
  sessionAffinity: None
  type: ClusterIP
