apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dotnet-blog
  name: dotnet-blog
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-blog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dotnet-blog
    spec:
      containers:
      - name: dotnet
        image:  hpranchernode1.uemedgenta.com:30008/uem/netcoreapp:latest        
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /app/data
          name: mypd
        env:
        - name: ConnectionStrings__DefaultConnection
          value: 'server=dotnet-mysql;userid=root;password=password;database=testdb;'
      imagePullSecrets:
      - name: regcred
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: dotnet-data-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: dotnet-data-claim
   namespace: default
spec:
   accessModes:
    - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
   storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnet-blog
  name: dotnet-blog
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30006
    name: http
  selector:
    app: dotnet-blog
  sessionAffinity: None
  type: NodePort
---
