apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-blog
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 35
      - pause: {}
      - setWeight: 69
      - pause: {duration: 10}
      - setWeight: 90
      - pause: {duration: 10}
#      - setWeight: 80
#      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-blog
  template:
    metadata:
      labels:
        app: rollouts-blog
    spec:
      containers:
      - name: rollouts-blog
        image: 207080326074.dkr.ecr.ap-southeast-1.amazonaws.com/flask_blog:v10.0.4
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
