apiVersion: v1
kind: Service
metadata:
  name: rollouts-blog
  namespace: production
  labels:
    app: rollouts-blog
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    name: http
  - port: 9200
    protocol: TCP
    targetPort: 9200
    name: metrics
  selector:
    app: rollouts-blog
