apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demospringalien
  name: demospringalien
  namespace: app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demospringalien
  template:
    metadata:
      labels:
        app: demospringalien
    spec:
      containers:
      - image: nashadabdulrahiman/spring-app:22
        name: demospringalien
        
