apiVersion: v1
kind: Service
metadata:
  labels:
    app: demospringalien
  name: demospringalien
  namespace: app-ns
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30002
  selector:
    app: demospringalien
  
